baseURL = '/'
languageCode = 'en-us'
title = 'Alex Theobold'
theme = 'cactus'

[params]
  author = "Alex Theobold"
  info = "Programmer"
  description = "Musings on software, development and working in tech"
  keywords = "blog,developer,personal"
  since = 2022
  copywrite = "Alex Theobold"

  colortheme = "dark"
  mainSection = "posts"
  showallpostsonhomepage = true

  customCSS = ["css/custom.css"]

# Social links
[[params.social]]
  name = "Github"
  link = "https://github.com/theoboldalex/"
[[params.social]]
  name = "Twitter"
  link = "https://twitter.com/theoboldalex/"
[[params.social]]
  name = "linkedin"
  link = "https://linkedin.com/in/theoboldalex/"

