baseURL = 'https://theoboldalex.github.io'
languageCode = 'en-us'
title = 'Alex Theobold'
theme = 'cactus'

[params]
  author = "Alex Theobold"
  info = "Programmer"
  description = "Musings on software, development and technology"
  keywords = "blog,developer,personal"
  since = 2022
  copywrite = "Alex Theobold"

  colortheme = "dark"
  mainSection = "posts"

  customCSS = ["css/custom.css"]

# Menu links
# [[menu.main]]
#   name = "Blog"
#   weight = 1
#   url  = "posts/"

# Social links
[[params.social]]
  name = "Github"
  link = "https://github.com/theoboldalex/"
[[params.social]]
  name = "Twitter"
  link = "https://twitter.com/theoboldalex/"
[[params.social]]
  name = "linkedin"
  link = "https://linkedin.com/in/theoboldalex/"
