baseURL = '/'
languageCode = 'en-us'
title = 'Alex Theobold'
theme = 'cactus'

[markup]
  [markup.highlight]
    style = 'vulcan'

[params]
  author = "Alex Theobold"
  info = "Programmer"
  description = "Confessions of a Programmer on the Brink"
  keywords = "blog,developer,personal"
  since = 2022
  copywrite = "Alex Theobold"
  logo = "images/favicon.ico"

  colortheme = "light"
  # mainSection = "home"
  mainSectionTitle = "Musings"
  showallpostsonhomepage = true

  customCSS = ["css/custom.css"]

# Social links
[[params.social]]
  name = "Github"
  link = "https://github.com/theoboldalex/"
[[params.social]]
  name = "Twitter"
  link = "https://twitter.com/theoboldalex/"
[[params.social]]
  name = "linkedin"
  link = "https://linkedin.com/in/theoboldalex/"

[pagination]
  pagesize = 20
